# -*- coding: utf-8 -*-
"""Cópia de Programa definitivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zQQYVzzcpuQ8pzPv7wrdhLjkLdWhmwI
"""

# ==========================================================
#              CALCULADORA DE INATIVIDADE
# ==========================================================

from datetime import date, timedelta

# ================== CONSTANTES ==================

TEMPO_TOTAL_MASC = 10950
TEMPO_TOTAL_FEM = 9125
TEMPO_TOTAL_MILITAR = 9125

DATA_BASE_GERAL = date(2019, 12, 31)
DATA_BASE_GERAL_2 = date(2020, 1, 1)
DATA_BASE_MILITAR = date(2022, 1, 1)

TABELA_ACRESCIMO = {
    2021: 0,
    2022: 120,
    2023: 240,
    2024: 365,
    2025: 485,
    2026: 605,
    2027: 730,
    2028: 850,
    2029: 970,
    2030: 1095,
    2031: 1215,
    2032: 1335,
    2033: 1460,
    2034: 1580,
    2035: 1700,
    2036: 1825  # teto máximo
}



# ================== FUNÇÕES AUXILIARES ==================

def obter_sexo():
    while True:
        sexo = input('Qual o sexo do militar? Digite [F] ou [M]: ').upper().strip()
        if sexo in ['F', 'M']:
            return sexo
        print('Sexo inválido! Digite apenas F ou M.')

def obter_inteiro(mensagem):
    while True:
        try:
            return int(input(mensagem))
        except ValueError:
            print('Entrada inválida! Digite um número inteiro.')

def calcular_acrescimo(ano):
    pass



# ================== INPUTS ==================

sexo = obter_sexo()
tempo_bruto_geral_2019 = obter_inteiro('Tempo geral em 2019: (DIAS) ')
tempo_bruto_militar_2019 = obter_inteiro('Tempo militar em 2019:(DIAS) ')
desconto_le_2017 = obter_inteiro('Licença Especial convertida após 24/07/2017: (DIAS) ')
desconto_le_2019 = obter_inteiro('Licença Especial convertida após 31/12/2019: (DIAS) ')
tempo_privado_2019 = obter_inteiro('Tempo privado averbado após 31/12/2019: (DIAS) ')
tempo_militar_2019 = obter_inteiro('Tempo militar averbado após 31/12/2019: (DIAS) ')




# ================ CONDICIONAL IF MASC OU FEM ==================

if sexo == 'M':
  tempo_total = TEMPO_TOTAL_MASC
elif sexo == 'F':
  tempo_total = TEMPO_TOTAL_FEM



# ================== CÁLCULO TEMPO GERAL ==================

tempo_final_2019 = tempo_bruto_geral_2019 - desconto_le_2019 - tempo_privado_2019 - tempo_militar_2019 # Tempo final em 2019

faltava_sem_acrescimo = tempo_total - tempo_final_2019 # Quanto militar faltaria completar depois de 2019 sem acréscimo

data_completou_sem_acrescimo = DATA_BASE_GERAL_2 + timedelta(days=faltava_sem_acrescimo)  # A data que completaria sem o acrescimo

acresimo_17 = int(faltava_sem_acrescimo * 0.17) # Valor do acrescimo calculado 17 % do que faltaria do tempo total, com o que já tinha em 2019

faltava_com_acrescimo = faltava_sem_acrescimo + acresimo_17 - tempo_militar_2019 - tempo_privado_2019 - desconto_le_2019 # Total de dias que falta somado com o acréscimo

data_completou_com_acrescimo = DATA_BASE_GERAL_2 + timedelta(days=faltava_com_acrescimo) # A data que completaria com o acrescimo


# ================== CÁLCULO TEMPO MILITAR ==================

tempo_final_2019_militar = tempo_bruto_militar_2019 - desconto_le_2017 - tempo_militar_2019

tempo_militar_2021 = tempo_final_2019_militar + 731

falta_tempo = TEMPO_TOTAL_MILITAR - tempo_militar_2021 - tempo_militar_2019

data_completou_sem_acrescimo_militar = DATA_BASE_MILITAR + timedelta(days=falta_tempo) - timedelta(days=tempo_militar_2019)


# ================== CÁLCULO ACRÉSCIMO MILITAR ==================

# ================== CÁLCULO ACRÉSCIMO MILITAR ==================

ano_referencia = max(
    data_completou_com_acrescimo.year,
    data_completou_sem_acrescimo_militar.year
)

while True:

    # pega pedágio da tabela
    if ano_referencia >= 2036:
        acrescimo = 1825
    else:
        acrescimo = TABELA_ACRESCIMO.get(ano_referencia, 0)

    # soma o pedágio na data que completaria sem pedágio
    data_final = data_completou_sem_acrescimo_militar + timedelta(days=acrescimo)

    # pega o maior ano entre geral e militar
    novo_ano = max(data_final.year, data_completou_com_acrescimo.year)

    # se estabilizou, para o loop
    if novo_ano == ano_referencia:
        break

    # senão recalcula
    ano_referencia = novo_ano









# ================== IMPRESSÖES NA TELA  ==================


print('''
================= TEMPO GERAL =================''')
print(f'Tempo Geral em 31/12/2019: {tempo_final_2019} dias')
print(f'Faltava sem o acréscimo no Tempo Geral: {faltava_sem_acrescimo} dias')
print(f'Data que completaria sem Acréscimo: {data_completou_sem_acrescimo:%d/%m/%Y}')
print(f'Acréscimo 17%: {acresimo_17} dias')
print(f'Faltava com o acréscimo no Tempo Geral: {faltava_com_acrescimo} dias')
print(f'DATA FINAL GERAL: {data_completou_com_acrescimo:%d/%m/%Y}')


print('''
================= TEMPO MILITAR =================''')
print(f'Tempo Militar (-LE) em 31/12/2019: {tempo_final_2019_militar} dias')
print(f'Tempo Militar em 31/12/2021: {tempo_militar_2021} dias')
print(f'Falta Tempo Militar: {falta_tempo} dias')
print(f'Data sem Acréscimo: {data_completou_sem_acrescimo_militar:%d/%m/%Y}')
print(f'Acréscimo aplicado: {acrescimo} dias')
print(f'DATA FINAL MILITAR: {data_final:%d/%m/%Y}')